### ISSUE TITLE
ParamDict.Set?

### ISSUE THREAD

**Issue by CobraCalle** [takuya-takeuchi/NcnnDotNet#12]
Hello,

sorry for the (perhaps dumb) question, but I`m new to ncnn. I`m trying to port RealSR to c# and came to the following lines:

        ncnn::ParamDict pd;
        pd.set(0, 3);// bicubic
        pd.set(1, 4.f);
        pd.set(2, 4.f);
        bicubic_4x->load_param(pd);

...but the ParamDict-class does not have any method / constructor to "fill" the dict...

Do I get something wrong here? Can anyone help me with thsi?

Thanks a lot

Carl

**Comment by takuya-takeuchi** [comment]
@CobraCalle 
Yes. ParamDict has no method.
Because current implementation has minimum interfaces to run some examples which ncnn teams provides.

**Comment by takuya-takeuchi** [comment]
no response
