### ISSUE TITLE
Cannot build NcnnDotNet.Native

### ISSUE THREAD

**Issue by lyxzhl** [takuya-takeuchi/NcnnDotNet#13]
When I run "pwsh BuildWindows.ps1", it said "Error: This platform is not support". Could you please upload NcnnDotNetNative.dll?

**Comment by takuya-takeuchi** [comment]
@lyxzhl 
Do you use PowerShell Core rather than PowerShell?
PowerShell does not support `global:IsWindows`, `global:IsLinux` and `global:IsMacOS`

**Comment by takuya-takeuchi** [comment]
@lyxzhl 
> Could you please upload NcnnDotNetNative.dll?

You can extract *.nuget file and get *.dll.

**Comment by takuya-takeuchi** [comment]
no response
