### ISSUE TITLE
Mat from Bitmap or byte[]

### ISSUE THREAD

**Issue by hueligton** [takuya-takeuchi/NcnnDotNet#14]
It's possible to have a way to get a Mat from a Bitmap or a byte[]?

Right now I need to create a Bitmap, use ToMap Extension from OpenCVSharp then I could use Mat.FromPixels.

Would be much simple if I could get the Mat use in NcnnDotNet directly.

**Comment by takuya-takeuchi** [comment]
@hueligton 
OpenCvSharp.Mat could expose Data (IntPtr) property.
Then, you could pass this to Mat constructor.

**Comment by takuya-takeuchi** [comment]
@hueligton 
Release 0.0.0.20210417 and it supports convert byte[] to Mat.

**Comment by takuya-takeuchi** [comment]
no response
