### ISSUE TITLE
how to implentment custom layer

### ISSUE THREAD

**Issue by goodtogood** [takuya-takeuchi/NcnnDotNet#17]
Hi,
I'm trying porting example of [yolov5](https://github.com/Tencent/ncnn/blob/master/examples/yolov5.cpp)
but there's a costom layer named **YoloV5Focus**
how to handle this case in c#
would you like to give some instructions on this?
thanks!

**Comment by takuya-takeuchi** [comment]
@goodtogood 
add code to

https://github.com/takuya-takeuchi/NcnnDotNet/tree/master/src/NcnnDotNet.Native/ncnn/layer/layers
https://github.com/takuya-takeuchi/NcnnDotNet/blob/4adb91be9dbaed1b33201355d1c03302019dbdab/src/NcnnDotNet.Native/ncnn/layer/layers/Layers.cpp
https://github.com/takuya-takeuchi/NcnnDotNet/tree/master/src/NcnnDotNet/Layer/Layers
