### ISSUE TITLE
Consider using ncnn's C API?

### ISSUE THREAD

**Issue by realivanjx** [takuya-takeuchi/NcnnDotNet#20]
ncnn does have a C api now https://github.com/Tencent/ncnn/blob/master/src/c_api.h

**Comment by takuya-takeuchi** [comment]
@realivanjx 
I'm not sure it works fine because there is no example program to use it.
I can not test it.

However, I think about it positively.

**Comment by realivanjx** [comment]
I am testing their `simpleopencv` API right now and so far works good.
https://gitlab.com/ivanjx/ncnnsharp

**Comment by takuya-takeuchi** [comment]
@realivanjx 
I started to develop for c api.
https://github.com/takuya-takeuchi/NcnnDotNet/tree/c_api

But api is too many. It should take many time to complete this task.

**Comment by takuya-takeuchi** [comment]
Add C API (not complete but works fine for object detection)
