### ISSUE TITLE
windows server运行出错

### ISSUE THREAD

**Issue by chen785161457** [takuya-takeuchi/NcnnDotNet#43]

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147385151-08677bd6-f556-4781-b00b-2d27455a9b4d.png)

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147385173-e065dbd4-a528-4894-beee-768405ef94cb.png)

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147396792-7bb656db-01df-4e21-995b-159f9f85de8d.png)

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147396796-4626a152-79d7-47e7-84af-195f7a66c4ed.png)

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147396800-22dd43e2-6b89-46cd-bab8-79d7c89910e6.png)

**Comment by chen785161457** [comment]
![image](https://user-images.githubusercontent.com/17880226/147396812-20471808-03b8-41d6-9ee4-c1878af66699.png)

**Comment by takuya-takeuchi** [comment]
@chen785161457 
NcnnDotNet depends pn VC++ runtimes so you must install VC++ runtime.
Please install Visual C++ 2017 Redistributable Package if you have not installed yet.

**Comment by chen785161457** [comment]
> @chen785161457 NcnnDotNet depends pn VC++ runtimes so you must install VC++ runtime. Please install Visual C++ 2017 Redistributable Package if you have not installed yet.

Ok  thank you .you are sure.
