### ISSUE TITLE
Do you support the scrfd algorithm model？

### ISSUE THREAD

**Issue by chen785161457** [takuya-takeuchi/NcnnDotNet#44]
https://github.com/deepinsight/insightface/tree/master/detection/scrfd
After I load the SCRFD_2.5G algorithm model, an error is reported

**Comment by takuya-takeuchi** [comment]
@chen785161457 
This code is python and it use mmdet rather than ncnn.
but this repo says about ncnn for android.
https://github.com/nihui/ncnn-android-scrfd

Please check code.

**Comment by chen785161457** [comment]
![QQ截图20211227133522](https://user-images.githubusercontent.com/17880226/147438637-83f65e3f-b97a-4d4a-b53c-e717b1e142f7.png)
![QQ截图20211227133313](https://user-images.githubusercontent.com/17880226/147438653-828119d2-2994-4af6-8108-49cb4c5e3c6d.png)
![QQ截图20211227133247](https://user-images.githubusercontent.com/17880226/147438963-6afa24fc-1555-454c-b66c-13aed90be129.png)

I use https://github.com/nihui/ncnn-android-scrfd . scrfd model, but the operation reports an error.

**Comment by chen785161457** [comment]
> @chen785161457 This code is python and it use mmdet rather than ncnn. but this repo says about ncnn for android. https://github.com/nihui/ncnn-android-scrfd
> 
> Please check code.

https://github.com/takuya-takeuchi/NcnnDotNet/issues/44#issuecomment-1001349759

**Comment by takuya-takeuchi** [comment]
ok, I'll go though code and model file on this weekend.
thanks.

**Comment by chen785161457** [comment]
> ok, I'll go through code and model file on this weekend. thanks.

If time permits, please take a look at this problem. Because the face detection effect inferred from other algorithm models is not as good as scrfd, especially for small faces, thanks.

**Comment by chen785161457** [comment]
> ok, I'll go through code and model file on this weekend. thanks.

I checked the scrfd example in ncnn, but I didn't understand the C + + code very well. The input and output of this algorithm model don't match with UltraFace. Can you help me look at the code and change UltraFace and give me an example? Thank you very much

**Comment by takuya-takeuchi** [comment]
@chen785161457 
I merged example program of SCRFD to develop branch.
https://github.com/takuya-takeuchi/NcnnDotNet/pull/45

**Comment by chen785161457** [comment]
> @chen785161457 I merged example program of SCRFD to develop branch. #45

ok,thanks!

**Comment by chen785161457** [comment]
I tried a picture with multiple faces, there is a problem, the result is always one face.

**Comment by chen785161457** [comment]
I checked your sample code, the problem lies in the nms method.

**Comment by takuya-takeuchi** [comment]
https://github.com/nihui/ncnn-android-scrfd/blob/3a546f10c47e3d5666bdd5ebf7b0ea5e47296e8c/app/src/main/jni/scrfd.cpp#L74

Is there any problem in this code?
If so, this behavior could be specification.

**Comment by chen785161457** [comment]
> https://github.com/nihui/ncnn-android-scrfd/blob/3a546f10c47e3d5666bdd5ebf7b0ea5e47296e8c/app/src/main/jni/scrfd.cpp#L74
> 
> Is there any problem in this code? If so, this behavior could be specification.

Not so. I tracked the code and found that the Area of each Rect class is the same, which leads to the error of NMS. You can debug to see if there is a problem with the rect class of NcnnDotnet source code.

**Comment by takuya-takeuchi** [comment]
ok, I understand. This nms method does not work because IntersectionArea does not take care of no-intersected area and Rect.Area returns wrong value always.

**Comment by takuya-takeuchi** [comment]
@chen785161457 
Fixed. 

![image](https://user-images.githubusercontent.com/6241854/148679758-9f9ae4d1-1b1d-4530-873f-a6984247b958.png)

**Comment by takuya-takeuchi** [comment]
no response
