### ISSUE TITLE
How to Build for Windows x86 using VS2019

### ISSUE THREAD

**Issue by ICU-UCI** [takuya-takeuchi/NcnnDotNet#47]
I tried to compile, but got the following error
![QQ截图20220210205243](https://user-images.githubusercontent.com/15668065/153412305-cbac7b6a-1c5d-4592-8034-1843e8dba72b.png)

**Comment by takuya-takeuchi** [comment]
After this, NcnnDotNetNative.dll should be in `src\NcnnDotNet.Native\build_win_desktop_cpu_x86`

![image](https://user-images.githubusercontent.com/6241854/153436548-33e55bd1-f9dd-4455-844d-2fc3fcf0fe68.png)

**Comment by ICU-UCI** [comment]
> @ICU-UCI I have never tried to build ncnndotnet by x86 but you can achive by the following steps
> 
>     1. Modify nuget\BuildWindows.ps1
> 
> 
> ```powershell
> $BuildTargets += [BuildTarget]::new("desktop", "cpu",    32, "$OperatingSystem-x86", "" )
> #$BuildTargets += [BuildTarget]::new("desktop", "cpu",    64, "$OperatingSystem-x64", "" )
> #$BuildTargets += [BuildTarget]::new("desktop", "vulkan", 64, "$OperatingSystem-x64", "" )
> ```
> 
>     2. Execute
> 
> 
> ```powershell
> $ pwsh BuildWindows.ps1
> ```

I modified this file ，But
![QQ图片20220211135708](https://user-images.githubusercontent.com/15668065/153544283-2bc1d972-3b68-497e-85e1-ddd9ccfe76d3.png)

**Comment by ICU-UCI** [comment]
> @ICU-UCI I have never tried to build ncnndotnet by x86 but you can achive by the following steps
> 
>     1. Modify nuget\BuildWindows.ps1
> 
> 
> ```powershell
> $BuildTargets += [BuildTarget]::new("desktop", "cpu",    32, "$OperatingSystem-x86", "" )
> #$BuildTargets += [BuildTarget]::new("desktop", "cpu",    64, "$OperatingSystem-x64", "" )
> #$BuildTargets += [BuildTarget]::new("desktop", "vulkan", 64, "$OperatingSystem-x64", "" )
> ```
> 
>     2. Execute
> 
> 
> ```powershell
> $ pwsh BuildWindows.ps1
> ```

I modified this file ,But it was unsuccessful 。

![QQ图片20220211135708](https://user-images.githubusercontent.com/15668065/153554363-151440eb-366d-444a-9fc4-397b9c5fefa1.png)

**Comment by takuya-takeuchi** [comment]
@ICU-UCI 
You must install PowerShell Core rather than PowerShell.
Legacy PowerShell does not support `$global:IsWindows` syntax.

**Comment by ICU-UCI** [comment]
Thanks for your answer, I guess there is still a problem with my computer environment，I gave up
![报错](https://user-images.githubusercontent.com/15668065/154395100-956f02c7-1970-44de-9d6b-f12004f665c7.png)
![QQ截图20220217104706](https://user-images.githubusercontent.com/15668065/154395117-08c2b801-e0ce-4f3f-bd2b-161e3399f467.png)

**Comment by takuya-takeuchi** [comment]
@ICU-UCI 
I'm not sure why your machine failed to build opencv.
But I suppose that you really want to get x86 binary.
So I upload it here.

[NcnnDotNetNative.zip](https://github.com/takuya-takeuchi/NcnnDotNet/files/8094953/NcnnDotNetNative.zip)

BTW, I can not understand x86 binary is required in the heyday of x64.
What purpose or target do you want x86t binary?

**Comment by ICU-UCI** [comment]
> @ICU-UCI I'm not sure why your machine failed to build opencv. But I suppose that you really want to get x86 binary. So I upload it here.
> 
> [NcnnDotNetNative.zip](https://github.com/takuya-takeuchi/NcnnDotNet/files/8094953/NcnnDotNetNative.zip)
> 
> BTW, I can not understand x86 binary is required in the heyday of x64. What purpose or target do you want x86t binary?

Thanks a lot! Because my software has some class libraries that involve hardware, they don't have x64, so they need x86

**Comment by takuya-takeuchi** [comment]
Latest nuget package support x86. close.
