### ISSUE TITLE
how to use?  no doc.

### ISSUE THREAD

**Issue by mz135135** [takuya-takeuchi/NcnnDotNet#48]
how to use?  no doc.

i'm try use this lib for yolov7.
but show is error.  how to use ?

doc???

**Comment by takuya-takeuchi** [comment]
@mz135135 
I have not checked ncnn code but I guess it requires custom operator.
It means that we should implement custom operator as C++ or C#.
https://github.com/takuya-takeuchi/NcnnDotNet/blob/4adb91be9dbaed1b33201355d1c03302019dbdab/examples/MobileNetV2SSDLite/Program.cs#L13

**Comment by mz135135** [comment]
您的邮件我已经收到！

**Comment by takuya-takeuchi** [comment]
@mz135135 
FYI, latest develop branch support yolox and yolov7.
Please check them.

**Comment by mz135135** [comment]
您的邮件我已经收到！
