### ISSUE TITLE
Memory overhead against original ncnn

### ISSUE THREAD

**Issue by andreae293** [takuya-takeuchi/NcnnDotNet#50]
Hello again
I was able to write a [c# port](https://github.com/andreae293/Stable-Diffusion.NET-NCNN/) of [stable-diffusion-ncnn](https://github.com/EdVince/Stable-Diffusion-NCNN) using your library and it works as intended.
However i noticed a big difference in terms of RAM usage

For example, the following code uses 5.5 GB of RAM 
```
Net net = new Net();
net.LoadParam("./assets/UNetModel-fp16.param");
net.LoadModel("./assets/UNetModel-fp16.bin");
```

while the original one in c++ uses only 3GB
```
net.load_param("assets/UNetModel-fp16.param");
net.load_model("assets/UNetModel-fp16.bin");
```

Its not vital for me to reduce memory usage but out of curiosity, do you have any idea of what is causing this?
Thanks for your time

**Comment by takuya-takeuchi** [comment]
@andreae293 
I'm not sure why ncnndotnet consume more gpu ram.
But I checked original code

https://github.com/EdVince/Stable-Diffusion-NCNN/blob/70c31d331563d0e6467d1218b7d1a2d5cf51bfde/x86/vs2019_opencv-mobile_ncnn-dll_demo/vs2019_opencv-mobile_ncnn-dll_demo/diffusion_slover.cpp#L3

````cpp
DiffusionSlover::DiffusionSlover()
{
	net.opt.use_vulkan_compute = false;
	net.opt.use_winograd_convolution = false;
	net.opt.use_sgemm_convolution = false;
	net.opt.use_fp16_packed = true;
	net.opt.use_fp16_storage = true;
	net.opt.use_fp16_arithmetic = true;
	net.opt.use_packing_layout = true;
	net.load_param("assets/UNetModel-fp16.param");
	net.load_model("assets/UNetModel-fp16.bin");

	ifstream in("assets/log_sigmas.bin", ios::in | ios::binary);
	in.read((char*)&log_sigmas, sizeof log_sigmas);
	in.close();
}
````

This code set true to `use_fp16_storage`. It could reduce usage of memory. ncnn could treat weight as fp32 if half precision is disable.
5,5GB could be twice of about 3.0GB.

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/209431576-e58cf2cc-10c9-45e1-8821-5f03915f77d3.png)

![image](https://user-images.githubusercontent.com/6241854/209431582-ad013fc7-3df1-40ac-a586-ef04f2aaded6.png)

**Comment by andreae293** [comment]
by setting the same flags in c#
```
            net.Opt.UseWinogradConvolution = false;
            net.Opt.UseVulkanCompute = false;
            net.Opt.UseSgemmConvolution = false;
            net.Opt.UseSgemmConvolution = false;
            net.Opt.UseFP16Packed = true;
            net.Opt.UseFP16Storage = true;
            net.Opt.UseFP16Arithmetic = true;
            net.Opt.UsePackingLayout = true;
```

i get 5.5 GB
without the flags i get 12 GB

**Comment by takuya-takeuchi** [comment]
How did you decide usage of memory is huge?
I checked you code,

https://github.com/andreae293/Stable-Diffusion.NET-NCNN/blob/e2e088dfdbea289438a49d0bc4563d468755a775/stable-diffusion/Form1.cs#L38

This statement initialize 3 objects that contains Net objects.
How much memory do PromptSolver and DecodeSolver use?
5.5 GB is total of 3 object, isn't it?

One more thing, I used stable release ncnn code.
https://github.com/Tencent/ncnn/tree/20221128

I'm not sure but there may have any issue in master branch of ncnn.

**Comment by andreae293** [comment]
Using the c# port, prompt slover uses 400MB, diffusion slover use 5GB , decoder 200 MB
Using the c++ code, prompt uses 400MB and diffusion uses 2.5 GB, decoder 100MB
so its 5.5 GB vs 3 GB
Yes i used the master release, i will try the stable one in the next days
Also, merry christmas

**Comment by takuya-takeuchi** [comment]
@andreae293 
We release 0.0.0.20221224 on today.

**Comment by andreae293** [comment]
Good news @takuya-takeuchi 
using the nuget you released yesterday, everything worked properly and now RAM usages are the same in both cases, c++ and c#
i should have used the stable releases from beginning.
thank you again
