### ISSUE TITLE
How to convert Mat to Bitmap ?

### ISSUE THREAD

**Issue by dominota** [takuya-takeuchi/NcnnDotNet#51]
Hi @takuya-takeuchi 

Thank you so much for the great library

I want to display Mat image on Winforms C# GUI. Could you help me create a function to convert Mat to Bitmap c#?

I gave some tries but i could not.

Thank you in advance

**Comment by takuya-takeuchi** [comment]
@dominota 
I think we need not to convert Mat to Bitmap because you should have original image before convert to Mat.
And NcnnDotNet does not have draw function for Mat.
So you can just show original image used for inference on WinForms.

I can't think of any usage scenarios to convert from Mat to Bitmap.

**Comment by takuya-takeuchi** [comment]
Ah, ok, It was misunderstanding.
You want to convert inference result like stable difusion, don't you?. In this case , ncnn returns image as Mat.

**Comment by takuya-takeuchi** [comment]
https://github.com/andreae293/Stable-Diffusion.NET-NCNN/blob/main/stable-diffusion/Form1.cs#L83

or 

Use Data property.

https://github.com/andreae293/Stable-Diffusion.NET-NCNN/blob/main/stable-diffusion/Form1.cs#L83

You can access pixel data via Data property.
And you can copy Data property to BitmapData object.

**Comment by dominota** [comment]
Thank you so much @takuya-takeuchi 

By the way, when will you update your library to latest ncnn with yolox support?

Best regards

**Comment by takuya-takeuchi** [comment]
@dominota 
Add yolov7 and yolox example tp develop branch.
I think you need using latest ncnndotnet.

thanks.

**Comment by dominota** [comment]
Thank you so much @takuya-takeuchi 

It woud be nice if there is a tutorial "How to build NcnnDotNetNative.dll from source". I load NcnnDotNet.sln and can build "NcnnDotNet" but the solution does not build NcnnDotNetNative.dll.

Thank you in advance.

**Comment by takuya-takeuchi** [comment]
@dominota 
You must install powershell (not built-in) and cmake.
Then, you kick only src\NcnnDotNet.Native\Build.ps1 like

````cmd
$ pwsh Build.ps1 Release cpu 64 desktop
````

if you installed vulkan, set env value and you can use it.

````cmd
$ VULKAN_SDK=D:\Works\Lib\VulkanSDK\1.2.189.0
$ pwsh Build.ps1 Release vulkan 64 desktop
````

**Comment by takuya-takeuchi** [comment]
Or you can delete reference of NcnnDotNet from examples and install nuget packge. It should work fine.

**Comment by dominota** [comment]
Thank you so much @takuya-takeuchi 
Please be patient to read my question. I need your help @takuya-takeuchi 
My goal is to build latest NcnnDotNetNative to use your new update yolov7 and yolox. The steps are:
+ Download and Install PowerShell-7.3.0-win-x64.exe : Done
+ Download and Install VulkanSDK-1.3.236.0: Done
+ Git clone NcnnDotNet: Done
+ Run Cmd as Administrator with your command: pwsh Build.ps1 Release vulkan 64 desktop.
Finally i got this error:

`C:\Users\Richman\Downloads\NcnnDotNet\NcnnDotNet-develop\src\NcnnDotNet.Native>pushd C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native

C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native>pwsh Build.ps1 Release vulkan 64 desktop
Build NcnnDotNet.Native
git submodule update --init --recursive

    Directory: C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----        31/12/2022 08:51 SÁNG                build_win_desktop_vulkan_x64
The system cannot find the path specified.
Get-Content: C:\Users\Richman\Documents\GitHub\NcnnDotNet\nuget\BuildUtils.ps1:753
Line |
 753 |     Get-Content "${env:temp}\vcvars.txt" | Foreach-Object {
     |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\Richman\AppData\Local\Temp\vcvars.txt' because it does not exist.
Start Build Protobuf
   cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Release
         -D BUILD_SHARED_LIBS=OFF
         -D CMAKE_INSTALL_PREFIX= C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native\build_win_desktop_vulkan_x64\protobuf\install
         -D protobuf_BUILD_TESTS=OFF
         -D protobuf_MSVC_STATIC_RUNTIME=OFF
         C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\protobuf\cmake
   cmake --build . --config Release --target install
End Build Protobuf
Start Build OpenCV
   cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Release
         -D BUILD_SHARED_LIBS=OFF
         -D BUILD_WITH_STATIC_CRT=OFF
         -D CMAKE_INSTALL_PREFIX="C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native\build_win_desktop_vulkan_x64\opencv\install"
         -D BUILD_opencv_world=OFF
         -D BUILD_opencv_java=OFF
         -D BUILD_opencv_python=OFF
         -D BUILD_opencv_python2=OFF
         -D BUILD_opencv_python3=OFF
         -D BUILD_PERF_TESTS=OFF
         -D BUILD_TESTS=OFF
         -D BUILD_DOCS=OFF
         -D BUILD_opencv_core=ON
         -D BUILD_opencv_highgui=ON
         -D BUILD_opencv_imgcodecs=ON
         -D BUILD_opencv_imgproc=ON
         -D BUILD_opencv_calib3d=OFF
         -D BUILD_opencv_features2d=OFF
         -D BUILD_opencv_flann=OFF
         -D BUILD_opencv_java_bindings_generator=OFF
         -D BUILD_opencv_ml=OFF
         -D BUILD_opencv_objdetect=OFF
         -D BUILD_opencv_photo=OFF
         -D BUILD_opencv_python_bindings_generator=OFF
         -D BUILD_opencv_shape=OFF
         -D BUILD_opencv_stitching=OFF
         -D BUILD_opencv_superres=OFF
         -D BUILD_opencv_video=OFF
         -D BUILD_opencv_videoio=ON
         -D BUILD_opencv_videostab=OFF
         -D WITH_CUDA=OFF
         -D BUILD_PROTOBUF=OFF
         -D WITH_PROTOBUF=OFF
         -D WITH_IPP=OFF
         -D WITH_FFMPEG=OFF
         -D WITH_ITT=OFF
         C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\opencv
   cmake build and install
End Build OpenCV
Start Build OpenCV
Skip Build OpenCV
End Build OpenCV
OpenCV could fail to build
End Build ncnn
Start Build NcnnDotNet.Native
   cmake -G "NMake Makefiles"
         -D CMAKE_BUILD_TYPE=Release
         -D BUILD_SHARED_LIBS=ON
         -D NCNN_VULKAN:BOOL=ON
         -D OpenCV_DIR="C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\NcnnDotNet.Native\build_win_desktop_vulkan_x64\opencv\install"
         -D ncnn_DIR="/lib/cmake/ncnn"
         -D ncnn_SRC_DIR="C:\Users\Richman\Documents\GitHub\NcnnDotNet\src\ncnn"
         ..
CMake Error at CMakeLists.txt:9 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/Richman/Documents/GitHub/NcnnDotNet/src/NcnnDotNet.Native/build_win_desktop_vulkan_x64/CMakeFiles/CMakeOutput.log".
   cmake --build . --config Release
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: nmake -f Makefile /nologo &&`

Could you point me which step i was wrong? 
Thank you in advance @takuya-takeuchi

**Comment by dominota** [comment]
> Or you can delete reference of NcnnDotNet from examples and install nuget packge. It should work fine.

@takuya-takeuchi Newest package from Nuget is updated with Yolov7 and Yolox ?

**Comment by takuya-takeuchi** [comment]
@dominota 
I think you didn't install Visual Studio 2017.
Therefore, you saw `Cannot find path 'C:\Users\Richman\AppData\Local\Temp\vcvars.txt' because it does not exist.`

> Newest package from Nuget is updated with Yolov7 and Yolox ?

Yes. latest package support new ncnn layers.
So you can have example probram work with following steps

1. git clone -b develop https://github.com/takuya-takeuchi/NcnnDotNet
2. cd NcnnDotNet\examples\YoloX
3. dotnet remove reference ..\..\src\NcnnDotNet\NcnnDotNet.csproj
4. dotnet add package NcnnDotNet
5. You can see that NcnnDotNet 0.0.0.20221224 was installed into YoloX.csproj
6. dotnet run -c Release -- dog.jpg

**Comment by dominota** [comment]
Yes, you'right
Thank you so much @takuya-takeuchi I got it works
By the way, i still can not convert Mat to Bitmap. May my skills are bad  :(
Please close this thread.
Thank you so much for the great work and keep up the good work!

**Comment by takuya-takeuchi** [comment]
@dominota 
I think result of Mat from extractor may be plane rather than pixel .

pixel is rgbrgbrgb
plan is rrrrrrrgggggbbbbb

So we have to do the following steps

1. ocnvert plane to pixels
2. pixels (Mat) to Bitmap

Latest package 0.0.0.20230101 support to_pixel functions.
And NcnnDotNet.Extensions.Drawing can convert Mat to Bitmap.

You can refer https://github.com/takuya-takeuchi/NcnnDotNet/blob/master/tests/NcnnDotNet.Extensions.Drawing.Tests/Extensions/DrawingExtensions.cs

**Comment by dominota** [comment]
Yes, thank you so much @takuya-takeuchi . 
Happy new year to you and your family!
Best regards,
