### ISSUE TITLE
NcnnDotNet v0.0.0.20230101 - System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by dominota** [takuya-takeuchi/NcnnDotNet#61]
Hi @takuya-takeuchi 
I just update to newest package from Nuget, try with Yolo3 sample and i get this error:

![image](https://user-images.githubusercontent.com/54459455/210241383-8a3e312d-a4a0-4a59-8842-eed49cb0aa2d.png)

I also try other samples and get the same error.
Is this a bug?

Thanks

**Comment by takuya-takeuchi** [comment]
@dominota 
Latest package has broken API.
So we must change

````diff
- var m = Cv2.ImRead(imagepath, CvLoadImage.Grayscale
+ var m = Cv2.ImRead(imagepath, CvLoadImage.AnyColor
````

It works fine.

**Comment by takuya-takeuchi** [comment]
https://github.com/takuya-takeuchi/NcnnDotNet/pull/62

**Comment by dominota** [comment]
It works, thanks
