### ISSUE TITLE
Speed in GPU is slower than Cpu

### ISSUE THREAD

**Issue by dominota** [takuya-takeuchi/NcnnDotNet#63]
Hi @takuya-takeuchi 
I test Yolov3 sample with two versions of NcnnDotnet (only cpu). 

With version 0.0.0.20230101 is more than 500 miliseconds
With version 0.0.0.20221224 is only 78 miliseconds

Both test on Windows 11 x64, Cpu version of NcnnDotNet, the same image size is 1000x754

Is there any changes in Api that can cause lower speed?

Thanks

**Comment by takuya-takeuchi** [comment]
@dominota 
I have no time to go through code but #61  may affect.
Previous code 

````csharp
    public enum CvLoadImage
    {

        Grayscale  = 1,

        Color = 3,

    }
````

now

````csharp
    public enum CvLoadImage
    {

        Unchanged = -1,

        Grayscale = 0,

        Color     = 1,

        AnyDepth  = 2,

        AnyColor  = 4

    }
````

Old code `Color` corresponds to current `Coplor + AnyDepth`.
In opencv ,library decide image channel num automatically if speficied `AnyColor`.
So this automatic decision may occur issue.

Could you change `AnyColor` to `Color`?

And which statement does it take time?

**Comment by dominota** [comment]
@takuya-takeuchi 
I'm sorry. I was wrong with codes. Thank you so much!

**Comment by dominota** [comment]
Fixed
