### ISSUE TITLE
mat from stream or byte array

### ISSUE THREAD

**Issue by goodtogood** [takuya-takeuchi/NcnnDotNet#9]
so excited to find NcnnDotNet , It's great work!
is it possible to transfer byte array or stream to mat ?
In .net core website, I want to infer the file (IFormFile) uploaed without saving it.
how to make it ? 
thx!

**Comment by takuya-takeuchi** [comment]
Are you talking about openCV.Mat rather than Ncnn.Mat?
No, there is no constructor for accepting byte array.
But I should provide it. Please give me time.

**Comment by goodtogood** [comment]
great to hear that.
both openCV.Mat and Ncnn.Mat are all ok.
thx!

**Comment by takuya-takeuchi** [comment]
Have a try.
7e8dcafc354a36382cc1fafb134e2b42c19c8ada

**Comment by takuya-takeuchi** [comment]
No response

**Comment by hueligton** [comment]
Can you please give an example how to use this constructor?

I don't know if a I get it.

**Comment by takuya-takeuchi** [comment]
@hueligton 
You can use new Mat constructors `Mat(int w, int h, byte[] data, ulong elemSize = 4u, Allocator allocator = null)`.
`data` is raw bitmap data. data is BGR if you must specify 3 as `elemSize`.

1. You get byte array from Bitmap object
2. Pass byte array to Mat constructor

**Comment by hueligton** [comment]
> @hueligton
> You can use new Mat constructors `Mat(int w, int h, byte[] data, ulong elemSize = 4u, Allocator allocator = null)`.
> `data` is raw bitmap data. data is BGR if you must specify 3 as `elemSize`.
> 
> 1. You get byte array from Bitmap object
> 2. Pass byte array to Mat constructor

This constructor only exist in develop branch. It's not available in NuGet yet.
